게시글 기본 CRUD 기능 구현
ducami-org/ducademi-server pull request #29
Opened 2024-04-15 11:26 UTC by alexipharmical

### 📄 관련 이슈
#27 #28 #20 #19 #18 #15 #11 #10

### 🐳 한 일
- 게시글 CRUD 로직 작성
- 멤버 & 강의 연결

### ☃️ 할 일
- S3 구현하기
- 게시글 페이징 적용하기

### 🔗 기타
- 처음이니까 많은 코드리뷰 해주시면 정말 감사드리겠습니다!!

2024-04-15 11:48 UTC, seu1a requested changes
좋습니다 ~ 👍 👍
제가 코멘트 달아놓은 것들은 수정해주시면 좋을 것 같아요 !!

2024-04-15 11:48 UTC, seu1a commented on src/main/java/ducami/org/ducademi/domain/board/controller/BoardController.java
> +}
음.. 스웨거는 추가하셨는데 문서 작성이 안되어있네요.
이슈 파서 진행해주시면 좋을 것 같아요. 👍 👍

2024-04-15 11:48 UTC, seu1a commented on src/main/java/ducami/org/ducademi/domain/board/dto/BoardRequestDTO.java
> +public class BoardRequestDTO { // 강의 idx 필요, 파일 필요
파일 업로드 로직 구현으로 이슈 따로 파주세요.
S3 연동되면 바로 작업하시면 됩니다.

2024-04-15 11:48 UTC, seu1a commented on src/main/java/ducami/org/ducademi/domain/board/dto/BoardResponseDTO.java
> +public class BoardResponseDTO { // 강의 idx 필요, 맴버 idx 필요
강의 ID랑 멤버 정보 보내주셨으면 좋겠어용

2024-04-15 11:53 UTC, seu1a commented
@heunseoRyu @whitenoise13 리뷰 부탁드립니다. 🐳

2024-04-15 11:58 UTC, alexipharmical commented on src/main/java/ducami/org/ducademi/domain/board/controller/BoardController.java
> +}
이슈 생성 완료했습니다~!

2024-04-15 12:26 UTC, heunseoRyu approved these changes
@RequiredArgsConstructor 적극활용하면 가독성 더욱 올라갈 것 같습니다.

2024-04-20 15:32 UTC, alexipharmical commented on src/main/java/ducami/org/ducademi/domain/board/service/BoardService.java
> +                () -> new IllegalArgumentException("해당 아이디가 존재하지 않습니다.")
근데 여기서는 member를 확인하는 게 아니라 boardIdx를 써야 하는 건데 이걸 써야 하는 게 맞나요? 다시 한번 확인 부탁드립니다..

2024-04-21 05:12 UTC, heunseoRyu commented
Update이기때문에 어떤 board인지 알아야해요👍그것에 더해 이 요청을 한 유저가 관리자가 맞는지 확인해야겠죠 따라서 작성자 idx와 board의 idx둘다 받아야 합니다😎

2024-04-21 12:36 UTC, alexipharmical commented on src/main/java/ducami/org/ducademi/domain/board/controller/BoardController.java
> +}
문서 작업은 나중에 하겠습니다!

2024-04-22 08:03 UTC, seu1a approved these changes
확인했습니다. 머지합니다 ✅✅

2024-04-22 08:04 UTC, merged